# -*- coding: utf-8 -*-
"""sentence similarity project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Qzivhp483qe_WR2GXljKGSBMSUgBlhio
"""

!pip install sentence-transformers

from sentence_transformers import SentenceTransformer,util
model = SentenceTransformer('all-MiniLM-L6-V2')
text1=input("Enter Text1:")
text2=input("Enter Text2:")
embedding1=model.encode(text1)
embedding2=model.encode(text2)
Similarity = util.cos_sim(embedding1,embedding2)
print("\nSimilarity Score:",round(float(Similarity),2))
if Similarity > 0.75:
  print("Similarity Level:High")
elif Similarity > 0.4:
  print("Similarity Level:Medium")
else:
  print("Similarity Level:Low")